language: node_js
node_js: "10"

git:
  depth: 3

branches:
  only:
    - master
  #  - /^greenkeeper/.*$/

services: mongodb
env:
  global:
    - NODE_ENV=test
    - DOCKER_FLAG=docker_test
    - MONGO_URI_TESTS=mongodb://localhost:27017/resume_prod
    - MONGO_URI=mongodb://localhost:27017/resume_prod
    - MONGO_USER=mongo
    - MONGO_PASS=mongo
    - PORT=3000
    - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
    - JWT_EXPIRATION_MINUTES=15

# script: yarn validate

# before_install: yarn global add greenkeeper-lockfile@1
before_script:
  # - greenkeeper-lockfile-update
  - yarn install
#  - npm run build:v2

# after_script: greenkeeper-lockfile-upload

# deploy:
# - provider: script
#   script: yarn deploy

after_success: yarn coverage
