version: '3.4'
services:
  # resume-app:
  #   image: afriedrichsen/resume-app:latest
  #   deploy:
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: '0.25'
  #         memory: '100M'
  #     restart_policy:
  #       condition: on-failure
  #   ports:
  #     - '2112'
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=2112
  #     - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
  #     - JWT_EXPIRATION_MINUTES=15
  #     - MONGO_URI=mongodb://mongo-dev:27017/resume_data
  #     - MONGO_USER=app_reader
  #     - MONGO_PASS=password
  resume-db:
    image: amazon/dynamodb-local
    ports:
      - '30004:8000'
    deploy:
      restart_policy:
        condition: on-failure
  # mongo-dev:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "37017:27017"
  #   environment:
  #     MONGO_INITDB_DATABASE: resume_data
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - ./app/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
