version: "3.2"
services:
  resume-app:
    image: afriedrichsen/core-projects:resumejs
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.25"
          memory: "100M"
      restart_policy:
        condition: on-failure
    ports:
      - "2112:2112"
    volumes:
      - /app/resume/config:/app/resume/config
    links:
      - resume-db
    depends_on:
      - resume-db
    networks:
      - friednet
  resume-db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - friednet
    links:
      - resume-app
networks:
  friednet: