version: "3"
services:
  app:
    # replace username/repo:tag with your name and image details
    image: afriedrichsen/core-projects:resumejs
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "2112:2112"
    networks:
      - webnet
networks:
  webnet: