version: "2"
services:
  resume-app:
    image: afriedrichsen/resume-app:latest
    ports:
      - "2112:2112"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
      - JWT_EXPIRATION_MINUTES=15
      - MONGO_URI=mongodb://ds141641.mlab.com:41641/resume_prod
      - MONGO_USER=app_reader
      - MONGO_PASS=ThePlaybookGameSucks2019
